version: '3'

services:

  nginx:
    image: nginx:1.19.4
    volumes:
      - ./docker/nginx/letsencrypt.conf:/etc/nginx/conf.d/letsencrypt.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
